Catch exception when fetching permissions
laravel-doctrine/acl pull request #38
Opened 2017-07-26 21:36 UTC by hultberg

Scenario: I had my own Permission class, and added a new column to it, and I get hit by exceptions when attempting to generate new migrations.

As this might cause problems when database structure has changed in
mapping, but users is attempting to execute doctrine:migrations commands
they get hit with exceptions and thus makes the commands unusable until
they change the vendor code. It's better in this situation to just catch
any exception and then logging it, hoping that users check their logs.

2017-07-26 21:41 UTC, hultberg commented
Errors on travis is not related to this MR.

2018-02-27 11:59 UTC, patrickbrouwers requested changes

2018-02-27 11:59 UTC, patrickbrouwers commented on src/Permissions/DoctrinePermissionDriver.php
> +    public function __construct(ManagerRegistry $registry, Repository $config, Log $log)
This should be the Psr LoggerInterface

2021-02-01 18:46 UTC, eigan commented
> I get hit by exceptions when attempting to generate new migrations.

Which exception? 

_(Sorry for the bump in this very old issue. Please ask for reopen if this is still a problem)_

2021-02-01 18:46 UTC, closed without merging