Changed tableExists check to be less resource intensive for large clusters
laravel-doctrine/acl pull request #44
Opened 2019-02-19 15:12 UTC by websmurf

The tableExists function executes a query that takes approximately 6 seconds on our database cluster.
Since this query is executed twice on every page load, requests are quite slow.

This method is a bit less resource intensive that the previous one

2019-02-20 14:50 UTC, vv12131415 requested changes
Mostly looks good, but can I get answers please

2019-02-20 14:50 UTC, vladysta commented on src/Permissions/DoctrinePermissionDriver.php
> +            return new EntityRepository(
Have you seen the https://github.com/laravel-doctrine/acl/commit/bf5084a79d904205eae82a059eef86f743866122 commit and those 2 issues https://github.com/laravel-doctrine/acl/issues/1 and https://github.com/laravel-doctrine/acl/issues/2 ?

2019-02-20 14:50 UTC, vladysta commented on tests/Permissions/DoctrinePermissionDriverTest.php
> -        $this->em->shouldReceive('getConnection')->once()->andReturn($connection);
don't really understand the "why" of deleting piece of the testcase. Can you please explain?

2019-02-20 14:50 UTC, vladysta commented on tests/Permissions/DoctrinePermissionDriverTest.php
> -        $schema = m::mock(MySqlSchemaManager::class);
same comment as above. Can you please explain?

2019-02-20 19:51 UTC, websmurf commented on src/Permissions/DoctrinePermissionDriver.php
> +            return new EntityRepository(
Yes, the try/catch statement i've added around the `findAll` method in `getAllPermissions` catches that error and makes sure that that exception will be caught.

2019-02-20 19:52 UTC, websmurf commented on tests/Permissions/DoctrinePermissionDriverTest.php
> -        $this->em->shouldReceive('getConnection')->once()->andReturn($connection);
Simple, that part of the code is removed as well, see the changes I've made to the getRepository method in DoctrinePermissionDriver.php

2019-02-22 11:33 UTC, vv12131415 approved these changes

2019-02-22 11:33 UTC, merged